import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import techniciansRouter from "./technicians";
import companiesRouter from "./companies";
import serviceOrdersRouter from "./service-orders";
import applicationsRouter from "./applications";
import ratingsRouter from "./ratings";
import dashboardRouter from "./dashboard";
import notificationsRouter from "./notifications";
import locationsRouter from "./locations";
import rankingsRouter from "./rankings";
import evidencesRouter from "./evidences";
import checkinRouter from "./checkin";
import plansRouter from "./plans";
import walletsRouter from "./wallets";
import aiRouter from "./ai";
import dispatchRouter from "./dispatch";
import visionRouter from "./vision";
import copilotRouter from "./copilot";
import knowledgeRouter from "./knowledge";
import auditRouter from "./audit";
import tenantRouter from "./tenant";
import signaturesRouter from "./signatures";
import crmRouter from "./crm";
import academyRouter from "./academy";
import communityRouter from "./community";
import apiKeysRouter from "./api-keys";
import contractsRouter from "./contracts";
import executiveRouter from "./executive";
import specialtiesRouter from "./specialties";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(techniciansRouter);
router.use(companiesRouter);
router.use(serviceOrdersRouter);
router.use(applicationsRouter);
router.use(ratingsRouter);
router.use(dashboardRouter);
router.use(notificationsRouter);
router.use(locationsRouter);
router.use(rankingsRouter);
router.use(evidencesRouter);
router.use(checkinRouter);
router.use(plansRouter);
router.use(walletsRouter);
router.use(aiRouter);
router.use(dispatchRouter);
router.use(visionRouter);
router.use(copilotRouter);
router.use(knowledgeRouter);
router.use(auditRouter);
router.use(tenantRouter);
router.use(signaturesRouter);
router.use(crmRouter);
router.use(academyRouter);
router.use(communityRouter);
router.use(apiKeysRouter);
router.use(contractsRouter);
router.use(executiveRouter);
router.use(specialtiesRouter);

export default router;
